name: CI

on:
  push:
  schedule:
    - cron: 0 11 * * 2
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gather metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            PuneetMatharu/cmake-format
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
